# Generated by Django 4.2.5 on 2023-09-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_delete_user_followers'),
        ('groups', '0004_group_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='grp_feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
                ('img', models.ImageField(upload_to='group/feed', verbose_name='Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='authentication.profiles', verbose_name='Author')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='groups.group', verbose_name='Group')),
            ],
        ),
    ]
