# Generated by Django 4.2.5 on 2023-09-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_grp_talks_about_grp_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='email',
            field=models.CharField(default=1, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='phone',
            field=models.CharField(default=1, max_length=50, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.CharField(default=1, max_length=50, verbose_name='Price For hire/Hour'),
            preserve_default=False,
        ),
    ]
