# Generated by Django 4.2.5 on 2023-09-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_email_group_phone_group_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='grp_feed',
            name='link',
            field=models.CharField(default=1, max_length=12350, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
