# Generated by Django 4.2.5 on 2023-09-17 14:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0012_delete_user_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Event Name')),
                ('start_date_time', models.DateTimeField(verbose_name='start Date and Time')),
                ('end_date_time', models.DateTimeField(verbose_name='End Date and Time')),
                ('center', models.CharField(max_length=250, verbose_name='Center/organization Name')),
                ('location', models.CharField(max_length=250, verbose_name='Location')),
                ('calender', models.URLField(max_length=25000, verbose_name='Add to Calender link')),
                ('about', ckeditor.fields.RichTextField(verbose_name='About 1')),
                ('card', models.ImageField(upload_to='event/card', verbose_name='card 285*150')),
                ('banner', models.ImageField(upload_to='event/banner', verbose_name='Banner 475*350')),
                ('poster', models.ImageField(upload_to='event.poster', verbose_name='Poster')),
                ('about2', ckeditor.fields.RichTextField(verbose_name='About 2')),
                ('entry', models.CharField(max_length=50, verbose_name='Entry Fee')),
                ('phone', models.CharField(max_length=50, verbose_name='Main Phone Number')),
                ('map', models.URLField(max_length=25000, verbose_name='Google link')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profiles', verbose_name='Organizer')),
            ],
        ),
    ]
