# Generated by Django 4.2.5 on 2023-09-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
