# Generated by Django 4.2.5 on 2023-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_adv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
