# Generated by Django 4.2.5 on 2023-09-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.events', verbose_name='Event'),
            preserve_default=False,
        ),
    ]
