# Generated by Django 4.2.5 on 2023-09-16 12:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('about', ckeditor.fields.RichTextField()),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('joined', models.CharField(max_length=50, verbose_name='Date Joined')),
                ('birthplace', models.CharField(max_length=250, verbose_name='Birth Place')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('linkedin', models.CharField(max_length=50, verbose_name='Linkedin')),
                ('instagram', models.CharField(max_length=50, verbose_name='Instagram')),
                ('github', models.CharField(max_length=50, verbose_name='Github')),
                ('dob', models.CharField(max_length=50, verbose_name='DOB')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('phono', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('price', models.CharField(max_length=50, verbose_name='Freelancers Price / Hour')),
                ('image', models.ImageField(upload_to='profile/image', verbose_name='Profile Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
