# Generated by Django 4.2.5 on 2023-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profiles_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
