# Generated by Django 4.2.5 on 2023-09-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profiles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='about',
            field=models.TextField(verbose_name='About'),
        ),
        migrations.CreateModel(
            name='user_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=250, verbose_name='Technology')),
                ('image', models.ImageField(upload_to='user/skill', verbose_name='Logo ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profiles', verbose_name='Profile - User')),
            ],
        ),
    ]
