# Generated by Django 4.2.5 on 2023-09-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profiles_about_user_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=250, verbose_name='Year ')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('company', models.CharField(max_length=250, verbose_name='Company/organisation')),
                ('des', models.TextField(verbose_name='Short Description')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profiles', verbose_name='Profile - User')),
            ],
        ),
    ]
