# Generated by Django 4.2.5 on 2023-09-17 16:44

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_delete_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(default=authentication.models.get_random_default_image, upload_to='profile/image', verbose_name='Profile Photo'),
        ),
        migrations.CreateModel(
            name='core_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profiles', verbose_name='Name')),
            ],
        ),
    ]
