# Generated by Django 4.2.5 on 2023-09-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_profiles_image_core_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=250, verbose_name='Technology')),
                ('image', models.ImageField(upload_to='user/skill', verbose_name='Logo ')),
            ],
        ),
    ]
