# Generated by Django 4.2.5 on 2023-09-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_skills',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user_skills',
            name='tech',
        ),
        migrations.AddField(
            model_name='user_skills',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='authentication.skills', verbose_name='Skill'),
            preserve_default=False,
        ),
    ]
