# Generated by Django 4.2.5 on 2023-09-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_profile_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_rating',
            name='rating',
            field=models.IntegerField(verbose_name='Rating'),
        ),
    ]
