# Generated by Django 4.2.5 on 2023-09-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_profile_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=450, verbose_name='College, Location')),
                ('start_year', models.CharField(max_length=250, verbose_name='Start Year ')),
                ('end_year', models.CharField(max_length=250, verbose_name='end Year ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profiles', verbose_name='Profile - User')),
            ],
        ),
    ]
