# Generated by Django 4.2.5 on 2023-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_user_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_education',
            name='college',
            field=models.CharField(default=1, max_length=450, verbose_name='College, Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_education',
            name='course',
            field=models.CharField(max_length=250, verbose_name='Course'),
        ),
    ]
