# Generated by Django 4.2.5 on 2023-09-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_user_education_college_alter_user_education_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='origaniser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profiles', verbose_name='Name')),
            ],
        ),
    ]
